"""empty message

Revision ID: 3daa086086f8
Revises: 59fccf00e002
Create Date: 2023-01-24 16:43:23.147070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daa086086f8'
down_revision = '59fccf00e002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=12), nullable=True),
    sa.Column('hora', sa.String(length=12), nullable=True),
    sa.Column('etapa', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
