"""empty message

Revision ID: d23f10e730d8
Revises: cbb0deab972c
Create Date: 2023-01-26 01:23:13.288839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23f10e730d8'
down_revision = 'cbb0deab972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
