"""empty message

Revision ID: fa312b161fe1
Revises: d23f10e730d8
Create Date: 2023-01-26 02:11:38.276515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa312b161fe1'
down_revision = 'd23f10e730d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.LargeBinary(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
